In [2]:
import numpy as np 
import pandas as pd 
import torch 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
# scaling the data 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
y_train

377    B
147    B
420    B
322    B
212    M
      ..
7      M
244    M
27     M
286    B
287    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [14]:
y_train_encoded , y_test_encoded

(array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0]),
 array([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 1, 0]))

In [16]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

defining the model

In [24]:
from numpy import dtype


class MySimpleNN():

    def __init__(self , X):
        
        self.weights = torch.rand(X.shape[1] , 1 , requires_grad=True , dtype = torch.float64)
        self.bias = torch.rand(1 , dtype = torch.float64 , requires_grad=True)

    def forward(self , X):
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss(self , y_pred , y):
        # clamp prediction to avoid log(0) error 
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred))
        loss = loss.mean() #  i dont know why are we doing this but i wil find out 
        return loss

In [25]:
learning_rate = 0.1
epochs = 25

In [26]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.993381679018672
Epoch: 2, Loss: 3.857968589613589
Epoch: 3, Loss: 3.715186616648276
Epoch: 4, Loss: 3.5683796876954665
Epoch: 5, Loss: 3.4215520347940105
Epoch: 6, Loss: 3.2695482482693468
Epoch: 7, Loss: 3.1159771451992055
Epoch: 8, Loss: 2.963485224591137
Epoch: 9, Loss: 2.811633787120725
Epoch: 10, Loss: 2.6578730210108117
Epoch: 11, Loss: 2.5021744399032317
Epoch: 12, Loss: 2.345527290395661
Epoch: 13, Loss: 2.1913831619104265
Epoch: 14, Loss: 2.0409924635913144
Epoch: 15, Loss: 1.89224128336655
Epoch: 16, Loss: 1.7495807242590307
Epoch: 17, Loss: 1.6172222518033719
Epoch: 18, Loss: 1.4951287659591284
Epoch: 19, Loss: 1.3836746594515572
Epoch: 20, Loss: 1.2854638589503409
Epoch: 21, Loss: 1.2006317136712408
Epoch: 22, Loss: 1.1286984826525632
Epoch: 23, Loss: 1.0686123126033695
Epoch: 24, Loss: 1.0189025877617133
Epoch: 25, Loss: 0.977896731825522

In [27]:
model.bias

tensor([0.0538], dtype=torch.float64, requires_grad=True)

In [30]:
model.weights

tensor([[-0.2080],
        [-0.1538],
        [ 0.1854],
        [ 0.3161],
        [ 0.3278],
        [-0.2506],
        [-0.2143],
        [-0.5425],
        [-0.2311],
        [ 0.4950],
        [-0.2353],
        [ 0.5998],
        [-0.0667],
        [ 0.5518],
        [ 0.3362],
        [-0.3824],
        [ 0.4691],
        [ 0.3543],
        [ 0.3348],
        [ 0.2714],
        [-0.2305],
        [ 0.3128],
        [ 0.4964],
        [ 0.1017],
        [ 0.2633],
        [ 0.2652],
        [-0.5978],
        [-0.0111],
        [ 0.3269],
        [ 0.2920]], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.99).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6809787750244141